### ISSUE TITLE
S5: As a logged-in user, I want to view my own profile page. I want to be able to edit my own user profile to set and update my personal information.

### ISSUE THREAD

**Issue by LaurentLeFebve** [sopra-fs23-group-41/Server#10]
- [x] sopra-fs23-group-41/Client#9

- [x] sopra-fs23-group-41/Server#68

- [x] sopra-fs23-group-41/Client#53

- [x] sopra-fs23-group-41/Server#86

**Priority**: moderate
**Estimate**: 6h

Acceptance Criteria :
- [x] When a user accesses his/her own profile the ‘edit’ button is shown below.
- [x] By clicking the ‘edit’ button, a user can have a page to change their personal information including name, username, email, and password.
- [x] The number of games won should not be edited.
- [x] When saving the data, the user is redirected to the profile page and updated data is displayed.
