### ISSUE TITLE
S6: As a player of the game I want to be able to find the products that appeared in the game, so I can potentially buy them. 

### ISSUE THREAD

**Issue by LaurentLeFebve** [sopra-fs23-group-41/Server#11]
- [ ] sopra-fs23-group-41/Client#4

- [ ] sopra-fs23-group-41/Client#3

- [ ] sopra-fs23-group-41/Server#93

**Priority** : moderate
**Estimate** : 20h 

Acceptance Criteria :
- [ ] Upon completion of the game a button called “View Products” is displayed (in the “End of the Game” Screen).
- [ ] When this button is clicked the user is redirected to a page that contains a list of pictures, displaying all the items that were referenced during the game
- [ ] Upon clicking on a picture the user’s browser opens another tab that is directed to the product on Asos’s web-page.
