### ISSUE TITLE
S11: As a user I want to have access to a leaderboard so that I can compare myself to others (and friends)

### ISSUE THREAD

**Issue by tyagos** [sopra-fs23-group-41/Server#12]
- [ ] sopra-fs23-group-41/Client#55
- [ ] sopra-fs23-group-41/Server#89

- [ ] sopra-fs23-group-41/Client#40

- [ ] sopra-fs23-group-41/Server#50

- [ ] sopra-fs23-group-41/Server#52

Priority: minimal
Estimate: 5 hours 

Acceptance Criteria:
- [ ] The leaderboard is sorted in descending order by points obtained in the various games. Displayed are rank, username and amount of points of every registered user in the database.
- [ ] As a user I want to be able to click on any name on the leaderboard and be redirected to this user’s profile.
 
- [ ] The points are updated after every finished game.
- [ ] Optional: provide two leaderboards for single- and multiplayer respectively.
