### ISSUE TITLE
S7: As a logged in user I want to be able to receive a pin code from my friends and pass it to the game, which directs me to a Lobby, so that I and my friends can join the same game and we can experience the game together.

### ISSUE THREAD

**Issue by LaurentLeFebve** [sopra-fs23-group-41/Server#13]
- [ ] sopra-fs23-group-41/Client#59
- [ ] sopra-fs23-group-41/Client#70
- [ ] sopra-fs23-group-41/Server#92
- [ ] sopra-fs23-group-41/Server#91

**Priority** : critical
**Estimate** : 4h

Acceptance Criteria :
- [ ] There is a text field to fill in with a game code and a submit button to join a game.
- [ ] When the player fills in the Code to join a lobby, they are redirected to the corresponding lobby.
