### ISSUE TITLE
S10: As a player of the game I want to see the ranking of all the participants, so I can see who won and how I did compared to the other players. Furthermore, I would like to be able to go back to the Overview Screen to potentially start a new game. 

### ISSUE THREAD

**Issue by tyagos** [sopra-fs23-group-41/Server#14]
- [x] sopra-fs23-group-41/Client#32

- [x] sopra-fs23-group-41/Client#31

- [x] sopra-fs23-group-41/Client#28

- [x] sopra-fs23-group-41/Client#26

- [x] sopra-fs23-group-41/Client#23

- [x] sopra-fs23-group-41/Server#94

- [ ] #154

Priority : critical
Estimate : 8h 

Acceptance Criteria :
- [x] Once the last round of the game ends all players are automatically directed to the “End of the game” screen.
- [x] The end of the game screen contains a list of all participants ordered in a ranking, displaying the rank of each player and the number of points they achieved.
- [x] The “End of the game” screen contains a button “Go to Overview”. Upon clicking the button the user is directed to the Overview Screen.
- [x] The “End of the game” screen contains a button “View Products” (specified in S7)
- [x] The name of the winner is highlighted at the top of the screen
