### ISSUE TITLE
(Optional)S9: As the game master, I can define item categories before launching the game.

### ISSUE THREAD

**Issue by tyagos** [sopra-fs23-group-41/Server#16]
- [ ] sopra-fs23-group-41/Client#18

- [ ] sopra-fs23-group-41/Server#64

- [ ] sopra-fs23-group-41/Client#14

Priority : moderate
Estimate : 4h

Acceptance Criteria :
- [ ] The game room owner can access a list of all the possible categories through a dropdown box.
- [ ] When the category is chosen, the items appearing in the game will only be under this specific category.
- [ ] The game room owner can change any preferred category before the game is launched.
