### ISSUE TITLE
S1: As an unregistered user, I would like to register as a user with my chosen credentials, so I can be logged in and as an already registered user I want to login with my credentials to access the services that are only available to registered users and to get to the overview and be able to enjoy every feature of the game. 

### ISSUE THREAD

**Issue by LaurentLeFebve** [sopra-fs23-group-41/Server#5]
- [ ] sopra-fs23-group-41/Client#47

- [ ] sopra-fs23-group-41/Server#81

- [ ] sopra-fs23-group-41/Client#48

- [ ] sopra-fs23-group-41/Client#24
- [ ] sopra-fs23-group-41/Client#68

**Priority**: Critical
**Estimate**: 15h

Acceptance Criteria: 
- [ ] The user shall enter his credentials in a form, which consist of a unique username, name, password and email.
- [ ] In case of some error, e.g. username already exists, a pop-up will appear.
- [ ] The user will be automatically logged in and redirected to the overview, after successfully registering.
- [ ] login form that takes the credentials, email or username and password of a user and checks if they exist, logs the user in or give error
- [ ] if the user is verified to be logged in, the user gets directed to the overview and else gets redirected to the login/registration
