### ISSUE TITLE
S13: As the minigame "Guess The Price", I want to provide a fun experience to users. In order to be able to do that I fetch the currently most bought items of Asos and create a quiz. In the quiz I provide 4 buttons with different price tags and a picture of an item and the players have to guess the proper price. 

### ISSUE THREAD

**Issue by tyagos** [sopra-fs23-group-41/Server#6]
- [ ] sopra-fs23-group-41/Server#101
- [ ] sopra-fs23-group-41/Server#102

- [ ] sopra-fs23-group-41/Client#25

- [ ] sopra-fs23-group-41/Client#27

- [ ] sopra-fs23-group-41/Client#29

- [ ] sopra-fs23-group-41/Server#32

- [ ] sopra-fs23-group-41/Client#49
- [ ] sopra-fs23-group-41/Server#96

- [ ] sopra-fs23-group-41/Client#30
- [ ] sopra-fs23-group-41/Client#63
- [ ] sopra-fs23-group-41/Client#64
- [ ] sopra-fs23-group-41/Client#65
- [ ] sopra-fs23-group-41/Server#99
- [ ] sopra-fs23-group-41/Client#67
- [ ] sopra-fs23-group-41/Client#91

Priority : critical
Estimate : 50 hours

Acceptance Criteria :
- [ ] When the minigame gets started by the game master, a countdown is provided in order that all players can start the quiz at the same time.
- [ ] Upon the ending of the countdown, the image and the buttons with the price tags appear and the player can guess the price.
- [ ] The question gets distributed to all players and they all have the same amount of time to guess the price.
- [ ] The time each user needs to make a guess is measured. 
- [ ] When the time is up, the correct answer is displayed and each player gets points assigned, based on the time they need to guess and the current scoreboard is displayed.
- [ ] At the end of the game each player is redirected to the “End of game” screen.
