### ISSUE TITLE
S3: As a user I would like to select between the different game modes, in order to get to play the kind of game I want. 

### ISSUE THREAD

**Issue by LaurentLeFebve** [sopra-fs23-group-41/Server#7]
- [ ] sopra-fs23-group-41/Client#61
- [ ] sopra-fs23-group-41/Client#58

- [ ] sopra-fs23-group-41/Server#85

**Priority**: Critical
**Estimate**: 15h

Acceptance Criteria:
- [x] Upon clicking “Select Game Mode” the user shall first choose between single- or multiplayer, both represented by a button.
- [ ] After clicking on one of the buttons the user is directed to a list of either single- or multiplayer game modes, from which she/he can choose.
- [ ] Upon selecting a multiplayer game mode the user is considered as the “Game Master” and directed to the “Game Master Screen”, where he defines the settings of the game, as specified in S9. After defining the settings he can press the “Start game” button and subsequently every participant is directed to the start of the game.
