### ISSUE TITLE
S12: (Higher or Lower Game Mode) As a creator of the “Show me the money” I would like to be able to offer a game mode that is both single player and multiplayer in order to cover multiple preferences of a user

### ISSUE THREAD

**Issue by tyagos** [sopra-fs23-group-41/Server#8]
- [ ] sopra-fs23-group-41/Client#44

- [ ] sopra-fs23-group-41/Client#46

- [ ] sopra-fs23-group-41/Client#45
- [ ] sopra-fs23-group-41/Server#87

- [ ] sopra-fs23-group-41/Client#43

Priority : critical
Estimate : 30h 

Acceptance Criteria :
- [ ] Upon selecting the game mode higher/lower the user is directed to the Game lobby where two items are displayed. For one of those items the price tag is displayed.
- [ ] At the bottom of the screen two buttons “Higher” and “Lower” are displayed. The player has to guess whether the item, whose price tag is not displayed, is higher or lower.
- [ ] Upon clicking one of the two buttons, a message is displayed that shows whether the guess was correct or not. Furthermore, the previously unknown price tag is displayed and the product whose price was known is swapped with a new product, whose price is unknown. This indicates the start of the next round.
- [ ] The game ends when the specified amount of rounds are complete. The number of rounds is depicted in the top right corner of the screen. When the game ends the player is redirected to the “End of game” screen, as specified in S11.
