### ISSUE TITLE
S4: As a logged-in user, I want to get a list of all existing users, and inspect a user’s profile by selecting the username in a list of all registered users.

### ISSUE THREAD

**Issue by LaurentLeFebve** [sopra-fs23-group-41/Server#9]
- [x] sopra-fs23-group-41/Client#52

- [x] sopra-fs23-group-41/Client#21

- [x] sopra-fs23-group-41/Client#20

**Priority**: Critical
**Estimate**: 6h

Acceptance Criteria :
- [x] A user can get a view of a list of all registered users (users overview).
- [x] By clicking on a username in the users overview, the user is redirected to a profile page of the selected user.
- [x] The profile page contains the following data belonging to the selected user: username, online status, name, email and the number of games won.
- [x] The user overview and the profile page are only accessible for logged-in users.
- [x] The user can not edit other users’ profile pages.
